### ISSUE TITLE
dbr.min.js is missing

### ISSUE THREAD

**Issue by cjus** [dynamsoft-dbr/webassembly#1]
Tried running `node index.js`

```shell
Error: Cannot find module './dbr.min.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:571:15)
    at Function.Module._load (internal/modules/cjs/loader.js:497:25)
    at Module.require (internal/modules/cjs/loader.js:626:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/Users/cjustiniano/dev/pnxtech/webassembly/index.js:10:16)
    at Module._compile (internal/modules/cjs/loader.js:678:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:689:10)
    at Module.load (internal/modules/cjs/loader.js:589:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:528:12)
    at Function.Module._load (internal/modules/cjs/loader.js:520:3)
```

**Comment by yushulx** [comment]
@cjus Updated. Please try it again. Thanks.
